### ISSUE TITLE
Searching for all PPIs given a structure/sequence

### ISSUE THREAD

**Issue by aminsagar** [anton-bushuiev/PPIRef#1]
Hello.
Thanks for this awesome work.
I am trying to understand if there is a way to search for all PPIs for a query structure/sequence from the complete PPIRef database.
i.e. Suppose I want to find all the interactions made by Lysozyme in any of the available structures. Can I query the PPIRef database for Lysozyme sequence/structure?
I would be really grateful for any insights.
Best,
Amin.

**Comment by anton-bushuiev** [comment]
Hi Amin!

Thank you for your question!

Currently, it is only possible to search for PPIs with similar interfaces. Nevertheless, it is easy to extend the functionality for your use case of searching PPIs involving a similar sequence or a structure of one of the partners. This is a great idea and I will implement this in the first half of February.

Best wishes,
Anton

**Comment by aminsagar** [comment]
Thanks @anton-bushuiev for your quick response.
I look forward to this functionality.
To search for similar interfaces, would it be the correct approach to use the PPI comparison example and comare the complex of interest with all the available PDBs using idist and get top N with most cosine similarity?

**Comment by anton-bushuiev** [comment]
@aminsagar Yes, exactly. I would also recommend using Euclidean distance (named `L2` in the example) instead of cosine similarity. It was better validated and may lead to slightly better performance. Please note that for L2, the lower the value (distance), the more similar PPIs are.

Currently, I am updating PPIRef for the latest version of PDB. Then, I will upload it to Zenodo, so all the available PDBs can be downloaded, including their prepared iDist embeddings for fast retrieval. I will also add an example of how to retrieve from the whole PDB.

**Comment by anton-bushuiev** [comment]
Hi, @aminsagar !

In the new version of the package, you can search for similar PPIs given a query PPI interface or sequence. See the [Finding similar PPIs in Protein Data Bank section](https://github.com/anton-bushuiev/PPIRef?tab=readme-ov-file#finding-similar-ppis-in-protein-data-bank).

Please let me know if there are any issues with this. Thank you.

Anton

**Comment by aminsagar** [comment]
Thanks @anton-bushuiev 
This is fantastic!
I tried both sequence based and interface structure based search and they both worked perfectly.
Thanks again.
Amin.
